
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'slope_plugin_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Amplitude(object):
    def setupUi(self, Form):
        Form.setObjectName("AmplitudeForm")
        Form.resize(810, 530)

        # ---- Root layout ----
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(10)

        # ---- Splitter (horizontal) ----
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")

        # ---- Left: Table view ----
        self.tableView = QtWidgets.QTableView(self.splitter)
        self.tableView.setObjectName("tableView")

        # ---- Right: Sidebar with buttons ----
        self.rightPanel = QtWidgets.QWidget(self.splitter)
        self.rightPanel.setObjectName("rightPanel")

        self.rightLayout = QtWidgets.QVBoxLayout(self.rightPanel)
        self.rightLayout.setContentsMargins(0, 0, 0, 0)
        self.rightLayout.setSpacing(8)

        # Button
        self.pushButton = QtWidgets.QPushButton(self.rightPanel)
        self.pushButton.setObjectName("mainActionButton")
        self.rightLayout.addWidget(self.pushButton)

        # Spacer (to push buttons up)
        self.verticalSpacer = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.rightLayout.addItem(self.verticalSpacer)

        # Add splitter to layout
        self.horizontalLayout.addWidget(self.splitter)

        # Give the table more space initially
        self.splitter.setStretchFactor(0, 3)
        self.splitter.setStretchFactor(1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Amplitude Measurements"))
        self.pushButton.setText(_translate("Form", "Import As CSV"))